### ISSUE TITLE
Cannot import page from original PDF

### ISSUE THREAD

**Issue by rorycl** [rorycl/rm2pdf#2]
When using `rm2pdf` to import a PDF, the import sometimes fails with a panic.

The panic message typically includes the text "Expected xref to start with 'xref'".

This appears to be due to [gofpdi #16](https://github.com/phpdave11/gofpdi/issues/16), which is caused by gofpdi not supporting xref streams.

Action:
* Consider changing how PDFs are imported, 
* or help fix the xref stream problem

**Comment by rorycl** [comment]
Example error:

```
~/src/go-rm2pdf/rm2pdf -c blue -c red d46ced5f-1b26-431f-bafb-7dc2d68c3f43.pdf /tmp/100_planning_comments.pdf
panic: Failed to initialize parser: Failed to read pdf: Failed to read xref table: Expected xref to start with 'xref'.  Got: 47
```

**Comment by phpdave11** [comment]
@rorycl gofpdi v1.0.9 now supports xref streams

**Comment by rorycl** [comment]
Closing
