### ISSUE TITLE
Parse error with empty layers

### ISSUE THREAD

**Issue by steelgarden** [rorycl/rm2pdf#6]
It seems that if any page other than the last page has an empty layer with a non-empty layer above it (ie with a higher layer number), then the parser crashes with EOF. See the stack dump below. My workaround is to put a small, almost unnoticeable, dot in the first layer but it's not a great solution. I've never used Go before, nor do I have any idea about the format it needs to parse, but if you don't have the time/inclination to look into it then I'll give it a go.

/Users/ben/Library/Application Support/remarkable/desktop/17aae37e-1418-4d4e-bf5e-176d244b26a3.pdf page 1
rmfile /Users/ben/Library/Application Support/remarkable/desktop/17aae37e-1418-4d4e-bf5e-176d244b26a3/54b559eb-ac14-42a4-bb7f-58184c25cc61.rm
Maximum coordinates : {X:1215.938 Y:1546.1228}

/Users/ben/Library/Application Support/remarkable/desktop/17aae37e-1418-4d4e-bf5e-176d244b26a3.pdf page 2
rmfile /Users/ben/Library/Application Support/remarkable/desktop/17aae37e-1418-4d4e-bf5e-176d244b26a3/7a1eccc0-bd82-4378-98d2-456565e64486.rm
Maximum coordinates : {X:1215.938 Y:1546.1228}

/Users/ben/Library/Application Support/remarkable/desktop/17aae37e-1418-4d4e-bf5e-176d244b26a3.pdf page 3
rmfile /Users/ben/Library/Application Support/remarkable/desktop/17aae37e-1418-4d4e-bf5e-176d244b26a3/1d0019ec-62b0-4e37-96ba-fddc773aa81c.rm
Maximum coordinates : {X:1236.65 Y:1546.1228}

/Users/ben/Library/Application Support/remarkable/desktop/17aae37e-1418-4d4e-bf5e-176d244b26a3.pdf page 4
rmfile /Users/ben/Library/Application Support/remarkable/desktop/17aae37e-1418-4d4e-bf5e-176d244b26a3/7fa42b36-da00-4e1d-875f-39a8bba315f9.rm
Maximum coordinates : {X:1375.4968 Y:1813.187}

/Users/ben/Library/Application Support/remarkable/desktop/17aae37e-1418-4d4e-bf5e-176d244b26a3.pdf page 5
rmfile /Users/ben/Library/Application Support/remarkable/desktop/17aae37e-1418-4d4e-bf5e-176d244b26a3/aaa0a87f-e625-4940-9b81-2d7300ce85d0.rm
panic: EOF

goroutine 1 [running]:
github.com/rorycl/rm2pdf/rmparse.ParseSegment(0xc0001ac128, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/ben/Desktop/RemarkableColourTest/rm2pdf/rmparse/rmparse.go:251 +0x1d7
github.com/rorycl/rm2pdf/rmparse.(*RMFile).Parse(0xc0001ba000, 0x11dad47)
	/Users/ben/Desktop/RemarkableColourTest/rm2pdf/rmparse/rmparse.go:174 +0x165
github.com/rorycl/rm2pdf/rmpdf.constructPageWithLayers(0xc00020e0e0, 0x62, 0x7ffeefbff9c5, 0x24, 0x2a, 0xc00021a000, 0x85, 0x0, 0xed7f296f7, 0x1301ec0, ...)
	/Users/ben/Desktop/RemarkableColourTest/rm2pdf/rmpdf/pdf.go:122 +0x739
github.com/rorycl/rm2pdf/rmpdf.RM2PDF(0x7ffeefbff98b, 0x5e, 0x7ffeefbff9ea, 0xa, 0x0, 0x0, 0x1, 0xc0001ae2a0, 0x3, 0x4, ...)
	/Users/ben/Desktop/RemarkableColourTest/rm2pdf/rmpdf/pdf.go:227 +0x2f7
main.main()
	/Users/ben/Desktop/RemarkableColourTest/rm2pdf/main.go:74 +0x138

**Comment by rorycl** [comment]
Hi @steelgarden -- thanks for the report. This should be pretty easy to sort out.

If you have an example PDF and accompanying remarkable files to share those would be useful.

Rory

**Comment by steelgarden** [comment]
Thanks Rory!
Here's the simple test case I just made. I didn't use any template so no pdf attached. The full invocation that fails is as follows. Please let me know if I can help in any other way.

Your software is great BTW, without this I really couldn't mark scripts on the remarkable.

---------------------------

rm2pdf -v -t templates/A4.pdf 817d4122-b564-4af4-85f2-de829aa21b05 LayerTest.pdf 

/Users/ben/Desktop/RemarkableColourTest/rm2pdf/templates/A4.pdf page 1
rmfile /Users/ben/Library/Application Support/remarkable/desktop/817d4122-b564-4af4-85f2-de829aa21b05/a4e777c2-d8c7-452e-bde8-6df7eb8b1b95.rm
panic: EOF

goroutine 1 [running]:
github.com/rorycl/rm2pdf/rmparse.ParseSegment(0xc0001ac6d8, 0x0, 0x0, 0x0, 0x0, 0x0)
	/Users/ben/Desktop/RemarkableColourTest/rm2pdf/rmparse/rmparse.go:251 +0x1d7
github.com/rorycl/rm2pdf/rmparse.(*RMFile).Parse(0xc0001b8bd0, 0x11dad47)
	/Users/ben/Desktop/RemarkableColourTest/rm2pdf/rmparse/rmparse.go:174 +0x165
github.com/rorycl/rm2pdf/rmpdf.constructPageWithLayers(0x7ffeefbff945, 0x3f, 0x7ffeefbff9bf, 0x24, 0x1, 0xc0001aa5c0, 0xa, 0x0, 0xed7f2c33b, 0x1301ec0, ...)
	/Users/ben/Desktop/RemarkableColourTest/rm2pdf/rmpdf/pdf.go:122 +0x739
github.com/rorycl/rm2pdf/rmpdf.RM2PDF(0x7ffeefbff985, 0x5e, 0x7ffeefbff9e4, 0xd, 0x7ffeefbff945, 0x3f, 0x1, 0x0, 0x0, 0x0, ...)
	/Users/ben/Desktop/RemarkableColourTest/rm2pdf/rmpdf/pdf.go:227 +0x2f7
main.main()
	/Users/ben/Desktop/RemarkableColourTest/rm2pdf/main.go:74 +0x138



[layers.tar.gz](https://github.com/rorycl/rm2pdf/files/6217857/layers.tar.gz)

**Comment by steelgarden** [comment]
Thanks so much! Works perfectly.

**Comment by rorycl** [comment]
Closing with bugfix in [release 0.0.2](https://github.com/rorycl/rm2pdf/releases/tag/v0.0.2) where you can download a linux or osx (darwin/amd64) binary.

My fix in 0.0.2 seems to work with your test case -- thanks very much for sending it through.

Please let me know if the release works for you. Great to hear its useful!

**Comment by rorycl** [comment]
> Thanks so much! Works perfectly.

@steelgarden : grand -- thanks for the confirmation
