### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by alexjmiller** [rorycl/rm2pdf#7]
Hi Rory, Just wondering if you could reverse this, so that you can convert pdf to rm format the idea being that I want to make a ui kit that I can use to copy paste symbols or shapes into new pages. is it possible?

**Comment by rorycl** [comment]
Hi Alex. Sorry for the late reply. I guess you could in theory reverse the process. I'd refer to https://github.com/reHackable/maxio/blob/master/tools/rM2svg which converts from reMarkable lines format to svg. You could also look at https://github.com/rorycl/rm2pdf/blob/master/rmparse/rmparse.go where I've tried to make the structures as clear as possible. This isn't something I'm planning on at the moment, though. Regards, Rory

**Comment by rorycl** [comment]
Closing as wontfix.
