### ISSUE TITLE
Issue with RM2 or me?

### ISSUE THREAD

**Issue by Allaman** [rorycl/rm2pdf#8]
I copied the whole xochitl folder to my machine with `scp -r remarkable:~/.local/share/remarkable/xochitl .`.

Then I run `./rm2pdf-darwin-arm64 ../xochitl/b9b3e2fe-89b0-4d6c-8613-f95710aa4526.pdf output.pdf` and get the following error

```
panic: Failed to initialize parser: Failed to read pdf: Failed to read xref table: Failed to read prev xref: Failed to read prev xref: Failed to read prev xref: Unsupported /DecodeParms - only tested with /Columns <= 4 and /Predictor <= 12

goroutine 1 [running]:
github.com/phpdave11/gofpdi.(*Importer).SetSourceStream(0x14000121500, 0x140001d0500)
	/home/rory/go/pkg/mod/github.com/phpdave11/gofpdi@v1.0.13/importer.go:95 +0x1b4
github.com/jung-kurt/gofpdf/contrib/gofpdi.(*Importer).ImportPageFromStream(0x1400011c590, {0x102ba0738, 0x14000193000}, 0x3?, 0x3?, {0x102affcb6, 0x9})
	/home/rory/go/pkg/mod/github.com/jung-kurt/gofpdf@v1.16.2/contrib/gofpdi/gofpdi.go:54 +0x44
github.com/jung-kurt/gofpdf/contrib/gofpdi.ImportPageFromStream(...)
	/home/rory/go/pkg/mod/github.com/jung-kurt/gofpdf@v1.16.2/contrib/gofpdi/gofpdi.go:124
github.com/rorycl/rm2pdf/rmpdf.constructPageWithLayers({{0x1400017e340, 0x33}, 0x1400011c688, {0x0, 0x0}, 0x0, {0x102ba00b0, 0x140001d0220}, 0x0, {0x16d47add1, ...}, ...}, ...)
	/home/rory/src/go-rm2pdf/rmpdf/pdf.go:91 +0x2b4
github.com/rorycl/rm2pdf/rmpdf.RM2PDF({0x16d47adc6?, 0x14000106190?}, {0x16d47adfa, 0xa}, {0x0?, 0x102988ff8?}, {0x0, 0x0}, 0x0, {0x0, ...})
	/home/rory/src/go-rm2pdf/rmpdf/pdf.go:342 +0x318
main.main()
	/home/rory/src/go-rm2pdf/main.go:82 +0x14c
```

remarkable2 1.14
macOS 12.6 (ARM)

**Comment by rorycl** [comment]
Hi @Allaman 

Thanks for giving `rm2pdf` a go. There are a few possible reasons for this problem, none of which are to do with you!

1. the arm build doesn't work (it isn't tested)
2. there is a bug in the rm2pdf code (quite possible)
3. the importer library in rm2pdf, the `gofpdi` library, has a fault.

Based on the stack trace this looks like 3, the `gofpdi` library. There are a list of open issues for gofpdi [here](https://github.com/phpdave11/gofpdi/issues) and the failure to read xref table has come up a few times.

While that isn't easily fixable right now, you could look to resave the underlying pdf to rebuild the structure of the pdf to something that gofpdi will read more happily. You could try to resave the PDF using preview or (better) the `pdftk` tool which is available on homebrew. I have to do that from time to time.

`./rm2pdf-darwin-arm64 -h` has some rather verbose instructions on how to do that. Please let me know if that works for you.

However, to check that `rm2pdf` is working on your machine at all it would be great if you could clone the rm2pdf repo and cd into it. If you copy the binary you downloaded into that directory you should be able to run `/rm2pdf-darwin-arm64 testfiles/cc8313bb-5fab-4ab5-af39-46e6d4160df3 test.pdf`. This should make a file `test.pdf` from the reMarkable file bundle identified by that uuid. Would you mind giving that a go?

**Comment by Allaman** [comment]
Hi @rorycl,

thanks for your detailed comment. 

First the good news: `rm2pdf-darwin-arm64 testfiles/cc8313bb-5fab-4ab5-af39-46e6d4160df3 test.pdf` is working and test.pdf looks fine including all writings!

pdftk also does something because it _looks_ like it is working: 
```sh
pdftk b9b3e2fe-89b0-4d6c-8613-f95710aa4526.pdf output word.pdf.pdftk
mv b9b3e2fe-89b0-4d6c-8613-f95710aa4526.pdf b9b3e2fe-89b0-4d6c-8613-f95710aa4526.pdf.bak
mv word.pdf.pdftk b9b3e2fe-89b0-4d6c-8613-f95710aa4526.pdf
rm2pdf-darwin-arm64 b9b3e2fe-89b0-4d6c-8613-f95710aa4526.pdf test.pdf # no errror!
```
When I open test.pdf it contains 45 pages each page with the original's last page 😄 

The pdf I am refering to is not a remarkable notebook but a pdf which I have sent to my RM. Is this the root cause?
In my xochitl folder there are two kinds of pdfs:
1. those that I sent as pdf to the device and are readable on my computer
2. pdfs that seems to be broken and cannot be opened with a pdf viewer. Are those my notebooks? pdftk also does not read them.
  ```
pdftk 2f55dfe7-b503-4c86-9351-64c057344ee6.pdf output word.pdf.pdftk
Error: Invalid PDF: Rebuild failed: trailer not found.; Original message: PDF startxref not found.
Error: Failed to open input PDF file:
   2f55dfe7-b503-4c86-9351-64c057344ee6.pdf
Errors encountered.  No output created.
Done.  Input errors, so no output created.
```

PS:  I guess [here](https://github.com/rorycl/rm2pdf/blob/master/main.go#L44) should be no `cat`  in the help text 😉

**Comment by rorycl** [comment]
Hi @Allaman 

Thanks for looking into things further, that's really helpful.

Great to hear `rm2pdf-darwin-arm64 testfiles/cc8313bb-5fab-4ab5-af39-46e6d4160df3 test.pdf` is working. That means `rm2pdf` is working on `darwin/arm`, which is excellent.

I've always used `pdftk` with this form `pdftk <input> cat output <output>` but you are right, it doesn't look like `cat` is needed for this case although it is fine to have it.

I have no idea why your pdf is writing just the last page. If you have time it would be great if you could post a tarball of a simple 2 page pdf and all the associated files (after you have made annotations on those two pages).**

The reMarkable system renames pdf files to a unique uuid and then adds content, metadata and other json files associated with the pdf to the xochitl store. A reMarkable file bundle includes the content, metadata, pdf file and a directory of remarkable stroke files, one per page, in a directory with the same name, together with per-page -metadata.json files.

I have no idea why pdftk might not be able to read a renamed pdf file because (as far as I know) the reMarkable system does not convert original pdfs in any way. Perhaps some of your pdfs are corrupt?

** the files needed would be something along the following structure (with different uuids of course):
```
.
├── cc8313bb-5fab-4ab5-af39-46e6d4160df3
│   ├── 7794dbce-2506-4fb0-99fd-9ec031426d57-metadata.json
│   ├── 7794dbce-2506-4fb0-99fd-9ec031426d57.rm
│   ├── da7f9a41-c2b2-4cbc-9c1b-5a20b5d54224-metadata.json
│   └── da7f9a41-c2b2-4cbc-9c1b-5a20b5d54224.rm
├── cc8313bb-5fab-4ab5-af39-46e6d4160df3.content
├── cc8313bb-5fab-4ab5-af39-46e6d4160df3.metadata
├── cc8313bb-5fab-4ab5-af39-46e6d4160df3.pagedata
└── cc8313bb-5fab-4ab5-af39-46e6d4160df3.pdf
```

**Comment by Allaman** [comment]
I created two zips for you. [notebook.zip](https://github.com/rorycl/rm2pdf/files/9611187/notebook.zip) is obviously a notebook created on my remarkable. Works as expected! [pdf.zip](https://github.com/rorycl/rm2pdf/files/9611188/pdf.zip) is a simple pdf created with PDF Expert Pro and annotated on my remakable. The latter one does not work but this time with a different error.

As you probably not have seen my question on reddit may I ask you again whats the purpose of this tool? 🙈  

```
rm2pdf-darwin-arm64 pdf/7a288246-9315-4b59-9ca1-dd93798a33ed.pdf test.pdf
panic: Failed to get page resources: Page 2 does not exist!!

goroutine 1 [running]:
github.com/phpdave11/gofpdi.(*Importer).ImportPage(0x14000101500, 0x30?, {0x104c9bcb6, 0x9})
        /home/rory/go/pkg/mod/github.com/phpdave11/gofpdi@v1.0.13/importer.go:142 +0x318
github.com/jung-kurt/gofpdf/contrib/gofpdi.(*Importer).getTemplateID(0x1400000e5a0, {0x104d3c738, 0x14000169000}, 0x3?, {0x104c9bcb6?, 0x41?})
        /home/rory/go/pkg/mod/github.com/jung-kurt/gofpdf@v1.16.2/contrib/gofpdi/gofpdi.go:61 +0x4c
github.com/jung-kurt/gofpdf/contrib/gofpdi.(*Importer).ImportPageFromStream(0x1400000e5a0, {0x104d3c738, 0x14000169000}, 0x3?, 0x3?, {0x104c9bcb6, 0x9})
        /home/rory/go/pkg/mod/github.com/jung-kurt/gofpdf@v1.16.2/contrib/gofpdi/gofpdi.go:56 +0x60
github.com/jung-kurt/gofpdf/contrib/gofpdi.ImportPageFromStream(...)
        /home/rory/go/pkg/mod/github.com/jung-kurt/gofpdf@v1.16.2/contrib/gofpdi/gofpdi.go:124
github.com/rorycl/rm2pdf/rmpdf.constructPageWithLayers({{0x14000022360, 0x2c}, 0x1400000e698, {0x0, 0x0}, 0x0, {0x104d3c0b0, 0x140001a0230}, 0x0, {0x16b2de9a0, ...}, ...}, ...)
        /home/rory/src/go-rm2pdf/rmpdf/pdf.go:91 +0x2b4
github.com/rorycl/rm2pdf/rmpdf.RM2PDF({0x16b2de99c?, 0x140000101c0?}, {0x16b2de9c9, 0x8}, {0x0?, 0x104b24ff8?}, {0x0, 0x0}, 0x0, {0x0, ...})
        /home/rory/src/go-rm2pdf/rmpdf/pdf.go:342 +0x318
main.main()
        /home/rory/src/go-rm2pdf/main.go:82 +0x14c
```

**Comment by rorycl** [comment]
Hi @Allaman

I've very grateful that you took the time to prepare `notebook.zip` and `pdf.zip`. Thanks very much indeed.

I get the same error as you unless I resave the pdf using pdftk.

```
$ rm2pdf 7a288246-9315-4b59-9ca1-dd93798a33ed out.pdf
panic: Failed to get page resources: Page 2 does not exist!!

goroutine 1 [running]:
github.com/phpdave11/gofpdi.(*Importer).ImportPage(0xc000091500, 0x7f08ea543620?, {0x5e4fab, 0x9})
    /home/rory/go/pkg/mod/github.com/phpdave11/gofpdi@v1.0.13/importer.go:142 +0x377
github.com/jung-kurt/gofpdf/contrib/gofpdi.(*Importer).getTemplateID(0xc0000b4590, {0x62e2a0, 0xc000123000}, 0x3?, {0x5e4fab?, 0xc00010e9c0?})
    /home/rory/go/pkg/mod/github.com/jung-kurt/gofpdf@v1.16.2/contrib/gofpdi/gofpdi.go:61 +0x5d
...

$ pdftk 7a288246-9315-4b59-9ca1-dd93798a33ed.pdf cat output /tmp/7a288246-9315-4b59-9ca1-dd93798a33ed.pdf

$ mv 7a288246-9315-4b59-9ca1-dd93798a33ed.pdf 7a288246-9315-4b59-9ca1-dd93798a33ed.orig.pdf

$ mv /tmp/7a288246-9315-4b59-9ca1-dd93798a33ed.pdf ./

$ rm2pdf 7a288246-9315-4b59-9ca1-dd93798a33ed out.pdf
Some pen types were not found, and were forced to the fineliner style
pen: 21 occurrences: 3
```

I see someone has forked gofpdi; I'm going to see if that helps in this sort of case.

**Comment by Allaman** [comment]
I am happy when I could help. From my point of view this issue can be closed. rm2pdf works for pdfs and notebooks as well as Darwin ARM :)
